project:
  type: website

website:
  title: "Ruslan's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <script>MathJax = { chtml: { displayAlign: 'left'}};</script>


