---
title:  "Упражнения 2.1"
date: 2024-09-22
---
# Упражнения 2.1

## 2.1.1.

При движении материальной точки $M$
по прямой наблюдалась следующая 
зависимость проходимого пути $z$ от времени $t$:

i. $z=t^3 + t$
ii. $z = \frac{1}{1+t^2}$

Чему равна средняя скорость $v_{ср}$ движения
на интервале от момента времени $t$ до $t+\Delta t$?
Чему равна мгновенная скорость $v_{мгн}$ в 
момент $t$?

### Решение

#### $z=t^3 + t$

$$
\begin{flalign}
v_{ср} &= \frac{z(t+\Delta t)-z(t)}{\Delta t}\\
v_{ср} &= \frac{(t + \Delta t)^3 + (t + \Delta t) - (t^3 + t)}{\Delta t}\\
v_{ср} &= \frac{t^3 + 3t^2\Delta t +3t\Delta t^2 + \Delta t^3  + (t + \Delta t) - (t^3 + t)}{\Delta t}\\
v_{ср} &= \frac{3t^2\Delta t +3t\Delta t^2 + \Delta t^3 + \Delta t}{\Delta t}\\
v_{ср} &= 3t^2 + 1 +3t\Delta t + \Delta t^2\\
v_{мгн} &= 3t^2 + 1
\end{flalign}
$$

#### $z=\frac{1}{1+t^2}$

$$
\begin{flalign}
v_{ср} &= \frac{z(t+\Delta t)-z(t)}{\Delta t}\\
v_{ср} &= \frac{\frac{1}{1 + (t + \Delta t)^2}-\frac{1}{1+t^2}}{\Delta t}\\
\end{flalign}
$$
Рассмотрим числитель отдельно
$$
\begin{flalign}
\frac{1}{1 + (t + \Delta t)^2}-\frac{1}{1+t^2}= \frac{1+t^2-(1 + (t + \Delta t)^2)}{(1+t^2)(1 + (t + \Delta t)^2)}=
\frac{-2t\Delta t - \Delta t^2}{(1+t^2)(1 + (t + \Delta t)^2)}\\
\end{flalign}
$$

$$
\begin{flalign}
v_{ср} &= \frac{\frac{-2t\Delta t - \Delta t^2}{(1+t^2)(1 + (t + \Delta t)^2)}}{\Delta t}\\
v_{ср} &= \frac{-2t - \Delta t}{(1+t^2)(1 + (t + \Delta t)^2)}\\
v_{мгн} &= \frac{-2t}{(1+t^2)^2}\\
\end{flalign}
$$

## 2.1.2.
Для случая зависимости $z(t) = z_0 + bt + ct^2$ пути
от времени найдите величину $v_{ср}$ по формуле
$$
v_{ср} = \frac{z(t+\frac{1}{2}\Delta t)-z(t-\frac{1}{2}\Delta t)}{\Delta t}
$$
сравните 
полученное выражение со значением $v_{мгн}$ в 
момент времени $t$.

### Решение

Опять для удобства рассмотрим только числитель
$$
\begin{flalign}
z(t+\frac{1}{2}\Delta t)-z(t-\frac{1}{2}\Delta t)\\
z_0 +b (t + \frac{\Delta t}{2}) + c(t + \frac{\Delta t}{2})^2 
-z_0 -b (t-\frac{\Delta t}{2}) -c (t-\frac{\Delta t}{2})^2  \\
 bt + b\frac{\Delta t}{2} +c(\frac{\Delta t^2}{4}+\Delta t t+t^2)
-bt + b\frac{\Delta t}{2} -c(\frac{\Delta t^2}{4}-\Delta t t+t^2) \\
b\Delta t +2c\Delta t t\\
\end{flalign}
$$

Отсюда

$$
v_{ср} = \frac{\Delta t(b+2ct)}{\Delta t} = b+2ct
$$

## 2.2.1
Для алмаза количество $Q(Т)$ тепла
(в Дж), необходимое дли нагревания 1 кг 
вещества от $0$ до $T°C$, в пределах от $0$ до
$700-800°С$ хорошо передается следующей
эмпирической формулой:

$$Q(T)= 0.39657 T + 2.081×10^{-3}T^2 - 5.024×10^{-7}T^3$$

Найдите среднюю теплоемкость $c_{ср}$ алмаза
на интервале от $T$ до $(T+\Delta T)°С$, а также
(мгновенную) теплоемкость $c=c(Т)$ как 
функцию $T$. Чему равна для алмаза величина
$c(0)$, $c(100)$ и $c(500)$?

### Решение

$$
c_{ср} = 0.39657 + 0.002081(2T + \Delta T) -5.024×10^{-7}(3T^2 + 3\Delta T T + \Delta T^2)\\
$$

$$
c(T) = 0.39657 + 2.081×10^{-3}(2T) - 5.024×10^{-7}(3T^2)
$$

## 2.2.2.
Количество $Q(Т)$ тепла, 
необходимое для нагревания $1$ кг воды от $0$ до $Т°С$,
хорошо передается следующей эмпирической
формулой:
$$Q(T)=4186.68 T-8373.36×10^{-5} T^2 + 1256×10^{-6} T^{3}$$

Чему равна теплоемкость $c(Т)$ воды? Какое
значение принимает она при $T=10°$, $90°$?

## 2.2.3.
Докажите, что (для любого вещества
и при любой температуре Т) объемный 
коэффициент теплового расширения (т. е. 
отнесенная к единице объема «мгновенная скорость»
увеличения объема при росте температуры)
равен утроенному линейному коэффициенту
теплового расширения.