---
title:  "Упражнения 1.9"
date: 2024-08-30
---
# Упражнения 1.9

## 1.9.1.

Даны точка $М$ и прямая $l$:

i. $М=М(1,-1), l:y=x+1$
i. $М=М(0,-1), l: y=4$
i. $M=M(-2, 0), l: y=-x-2$
i. $M=М(0, 0)$ (начало координат), $l: y=\frac{3}{4}x-\frac{1}{4}$

Проведите через точку $М$ прямую $p$
перпендикулярную прямой $l$.

## 1.9.2.

Даны три точки $A_1$, $A_2$, $A_3$:

- $A_1(0, 0)$, $A_2(4, 3)$, $A_3(-6, 8)$
- $A_1(4, -4)$, $A_2(4, 0)$, $A_3(-1, 1)$
- $A_1(1, 2)$, $A_2(2, 1)$, $A_3(-1, 1)$

i) Найдите $\angle A_2 A_1 A_3$; 
ii) вычислите $S_{\triangle A_1 A_2 A_3}$; 
iii) чему равно $h_{A_1 A_2 A_3}$

## 1.9.3.

Даны две параллельные прямые $l$ 
и $l_1$:

i. $l$: $y=x+2$, $l_1$: $y=x-2$; 
ii. $l$: $3x-4y-1=0$, $l_1$: $-3x+4y=0$.

Чему равно расстояние $d$ между этими прямыми?

## 1.9.4.
Для той же точки $М$ и той же прямой
$l$, что и в упр. 1, найдите расстояние $h$ от $М$
до $l$.

## 1.9.5.

Пусть $A_1=A_1(x_1, y_1)$, $A_2=A_2(x_2, y_2)$
$A_3=A_3(x_3, y_3)$ и $A_4=A_4(x_4, y_4)$ — четыре точки;
докажите, что $A_1A_2 \perp A_3A_4$ тогда и только
тогда, когда
$(x_2-x_1)(x_4-x_3) + (y_2-y_1)(y_4-y_3)=0$

## 1.9.6.

Найдите, как преобразуется 
уравнение окружности 
$$(x-a)^2 + (y-b)^2-r^2 = 0$$ {#eq-cirle} при переходе к новым
координатам $x'$, $y'$ по формулам.
$$
\begin{cases}
x' = x \cos \alpha + y \sin \alpha + a\\
y' = —x \sin \alpha +y \cos \alpha + b
\end{cases}
$$ {#eq-transform}
Проверьте, что фигурирующие в (@eq-cirle)  величины
$a$ и $b$ меняют при этом свою величину (т. е. что
новое уравнение будет иметь ту же форму,
но с иными $a$ и $b$, а величина $r$ не меняется.

::: {.callout-tip title="Указание" collapse="true"}
Для решения этой задачи
удобно «обратить» формулы (@eq-transform), выразив
старые координаты $x$, $y$ через новые 
координаты $x'$, $y'$.
:::

## 1.9.7.

Докажите, что при переходе (6)
к другой системе координат сохраняют свою
форму: а) условие кг=к2 параллельности
двух прямых; б) условие (9) 
перпендикулярности двух прямых; в) формула (8) для угла
между прямыми; г) формула (10) для 
расстояния между параллельными прямыми; д) 
формула (И) для расстояния от точки до прямой;
е) формула (4) для площади треугольника;
ж) формула (1) для угла треугольника; з) 
формула (5) для расстояния от точки до прямой;
и) условие АгА2 j_ ^3^4 (см. упр. 5). [См.
указание к упр. 6.]