---
title:  "Упражнения 1.7"
date: 2023-03-09
---
# Упражнения 1.7


## 1.7.1.
Постройте кривые

* $$\frac{x^2}{4} + \frac{y^2}{9}-1=0$$
* $$\frac{(x+3)^2}{4} + \frac{(y-5)^2}{9}-1=0$$
* $$\frac{(x-3)^2}{9} + \frac{(y+5)^2}{4}-1=0$$

:::{admonition} Указание
:class: tip

При этом естественно 
воспользоваться тем, что линия $x^2 + y^2 -1=0$
представляет собой единичную окружность.
:::

## 1.7.2.
Постройте график функции $y=\sin(x)$,
взяв, например, восемь значении $x$ в 
интервале от $-\pi$ до $\pi$, различающихся между
собой на целые кратные величины $\pi/4$.
Воспользовавшись этим графиком, постройте
кривые:

{style=lower-roman}
1. $y=2\sin(x)$
2. $y=\sin(\frac{x}{2})$
3. $y=3\sin(3x)$
4. $y=\cos(x)$
5. $y=\cos(x)+\sin(x)=\sqrt{2}\sin(x+\frac{\pi}{4})$
6. $y=\cos^2(x) = \frac{1}{2}+\frac{1}{2}\cos(2x)$
7. $y=\sin^2(x) = \frac{1}{2}-\frac{1}{2}\cos(2x)$

:::{admonition} Указание
:class: tip
   
   Все эти линии можно построить, сдвигая, растягивая или сжимая
   синусоиду $y = \sin(x)$ для решения упр. iv), vi), vii) воспользуйтесь тождеством $\cos(x) = \sin(x+\pi/2)$
:::

## 1.7.3.

Постройте кривые:

{style=lower-roman}
1. $y=\pm\sqrt{х^2—1}$
2. $y=\pm\sqrt{х^2+1}$
3. $y=2\pm\sqrt{(х-1)^2-1}$
4. $4y^2+4y-x^2=0$

:::{admonition} Указание
:class: tip

Кривую i) постройте по точкам, выбрав в интервале от $-5$
до $+5$ двадцать значений $x$, различающихся
на $0.5$ (и кратных $0.5$). Преобразовав 
уравнения i) и ii) к виду $y^2-x^2+1=0$, соответственно
$x^2-y^2+1=0$, заметим, что ii) получается из
i) перестановкой $x$ и $y$. Для решения iv) 
запишите уравнение этой кривой в виде $4(y+\frac{1}{2})^2-x^2-1=0$ и получите ее, сдвигая
и сжимая кривую ii).
:::

## 1.7.4.

Выпишите уравнение кривой, 
полученной из кривой $y=x^3-x$ (см. рис. 5.3):

{style=lower-roman}
1. сжатием в направлении оси $Oy$ с 
коэффициентом $1/3$ (т. е. уменьшением в 3 раза всех вертикальных размеров); 
2. подстановкой
```{math}
x \rightarrow \frac{x}{2}
```
3. подстановкой 
```{math}
y \rightarrow -\frac{y}{2}
```

Изобразите полученные кривые на чертеже.

## 1.7.5.

Докажите, что растяжение (или
сжатие) единичной окружности $x^2+y^2—1=0$
к любой прямой с каким угодно 
коэффициентом растяжения (сжатия) переводит ее в 
эллипс.
:::{admonition} Указание
:class: tip
Эту задачу можно
сформулировать так: растяжение или сжатие
любой окружности $(x-a)^2+(y-b)^2-r^2=0$
к оси $x$, т. е. подстановка $y \rightarrow ky$, переводит
эту окружность в эллипс
:::

## 1.7.6.

Докажите что график произвольной
дробно-линейной зависимости 

$$y=\frac{ax+b}{cx+d}$$

между переменными $y$ и $x$, где $c\neq0$, $\Delta=ad-bc\neq0$,
может быть получен из графика обратной пропорциональности $y=\frac{k}{x}$
где $k=-\frac{\Delta}{c^2}$ переносом последнего графика
на $\frac{d}{c}$ влево (т.е. при $\frac{d}{c}<0$ переносом на $ |\frac{d}{c}| $ вправо и на $\frac{a}{c}$ вверх.

## 1.7.7.

Докажите, что каждую функцию
можно представить в виде суммы четной и 
нечетной функций.
:::{admonition} Указание
:class: tip
Воспользуйтесь тождеством

$$f(x) = \frac{1}{2}(f(x)+f(-x)+\frac{1}{2}(f(x)-f(-x))$$
:::

## 1.7.8.

Докажите, что никакие две из 
кривых (10а)—(10в) несводимы одна к другой
подстановками вида $x' = ax + p$, $y' = bx + q$ (где,
разумеется, $a \neq 0$, $b \neq 0$), равносильными
изменению начала отсчета величин $x$ и $y$
(переносу начала координат), сопровождаемому
изменением единиц измерения $x$ и $y$.

## 1.7.9.

Укажите правило, позволяющее 
судить по коэффициентам a, b, c, d зависимости
(9) о том, сводится ли она к виду (10а), (10б)
или (10в).